import { Option } from '../interfaces';

export const languageOptions: Option[] = [
  { shortCode: 'en', languageName: 'Inglés', fullLocaleCode: 'en-US' },
  { shortCode: 'es', languageName: 'Español', fullLocaleCode: 'es-ES' },
  { shortCode: 'fr', languageName: 'Francés', fullLocaleCode: 'fr-FR' },
  { shortCode: 'de', languageName: 'Alemán', fullLocaleCode: 'de-DE' },
  { shortCode: 'zh', languageName: 'Chino (Simplificado)', fullLocaleCode: 'zh-CN' },
  { shortCode: 'ja', languageName: 'Japonés', fullLocaleCode: 'ja-JP' },
  { shortCode: 'ko', languageName: 'Coreano', fullLocaleCode: 'ko-KR' },
  { shortCode: 'pt', languageName: 'Portugués', fullLocaleCode: 'pt-PT' },
  { shortCode: 'ru', languageName: 'Ruso', fullLocaleCode: 'ru-RU' },
  { shortCode: 'ar', languageName: 'Árabe', fullLocaleCode: 'ar-SA' },
  { shortCode: 'it', languageName: 'Italiano', fullLocaleCode: 'it-IT' },
  { shortCode: 'nl', languageName: 'Neerlandés', fullLocaleCode: 'nl-NL' },
  { shortCode: 'sv', languageName: 'Sueco', fullLocaleCode: 'sv-SE' },
  { shortCode: 'no', languageName: 'Noruego', fullLocaleCode: 'no-NO' },
  { shortCode: 'da', languageName: 'Danés', fullLocaleCode: 'da-DK' },
  { shortCode: 'fi', languageName: 'Finlandés', fullLocaleCode: 'fi-FI' },
  { shortCode: 'pl', languageName: 'Polaco', fullLocaleCode: 'pl-PL' },
  { shortCode: 'tr', languageName: 'Turco', fullLocaleCode: 'tr-TR' },
  { shortCode: 'cs', languageName: 'Checo', fullLocaleCode: 'cs-CZ' },
  { shortCode: 'hu', languageName: 'Húngaro', fullLocaleCode: 'hu-HU' },
  { shortCode: 'ro', languageName: 'Rumano', fullLocaleCode: 'ro-RO' },
  { shortCode: 'he', languageName: 'Hebreo', fullLocaleCode: 'he-IL' },
  { shortCode: 'th', languageName: 'Tailandés', fullLocaleCode: 'th-TH' },
  { shortCode: 'vi', languageName: 'Vietnamita', fullLocaleCode: 'vi-VN' },
  { shortCode: 'ms', languageName: 'Malayo', fullLocaleCode: 'ms-MY' },
  { shortCode: 'id', languageName: 'Indonesio', fullLocaleCode: 'id-ID' },
  { shortCode: 'uk', languageName: 'Ucraniano', fullLocaleCode: 'uk-UA' },
];
